<?php
/*
Guest List Collection Template - present a form to gather data from customer

Templates follow the PHP Heredoc format: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
Variables are parsed using PHP double quote syntax (ex: "My $variable, your {$you->variable}, our \'\$variables\'")

The following variables and objects are available in this template:
* $artist (object)
    * $artist->name - <User's Name>
    * $artist->id - system specific ID for artist (for retrieving artist-specific images, for example)
    * $artist->artistlinks - array of artist promotional links (see also: $links)
    * $artist->promoterlinks - array of associated promoter promotional links (see also: $links)
    * $artist->association - system specific ID for promoter (for retrieving promoter-specific images, for example)
* $links - HTML formatted artist and promoter promotional links
* $extrafields - HTML formatted form fields for collecting custom data
* $event (object)
    * $event->id - system specific ID for event (used when submitting form data)
    * $event->year - YYYY
    * $event->month - MM
    * $event->day - DD
    * $event->headliner - Headliner
* $title - <Day of Week> | MMM DD :: <User>'s Guest List :: <Headliner> (ex: "Thursday | Feb 09 :: Global Dance's Guest List :: TJR")
* $price21 - text representation of event price for 21+
* $price18 - text representation of event price for 18+
* $option_21plus - HTML for adding radio button to select 21 as age group (if available)
* $option_18plus - HTML for adding radio button to select 18 as age group (if available)
* $settings (object)
*/
return <<<END
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Sign-up on the guest list for Beta Nightclub by following this link." />
    <link rel="shortcut icon" href="http://www.betanightclub.com/favicon.ico" type="image/x-icon" />
    <link rel="image_src" href="http://tech.betanightclub.com/gl/fbicon.jpg" />
    <meta property="og:image" content="http://tech.betanightclub.com/gl/fbicon.jpg" />
    <meta property="og:title" content="$title" />
    <meta property="og:url" content="http://tech.betanightclub.com/gl/$event->id" />
    <meta property="og:type" content="article" />
    <meta property="article:expiration_time" content="{$event->year}-{$event->month}-{$event->day}T{$settings['expiration']['hour']}:{$settings['expiration']['minute']}-07:00" />
    <meta property="og:site_name" content="Beta Nightclub" />
    <meta property="og:description" content="Sign-up on the guest list for Beta Nightclub by following this link." />
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@betanightclub">
    <meta name="twitter:creator" content="@lb1justin">
    <meta name="twitter:title" content="$title">
    <meta name="twitter:description" content="Use this page to sign-up on for guest list access to Beta Nightclub on {$event->month}/{$event->day} featuring {$event->headliner}, courtesy of {$artist->name}.">
    <meta name="twitter:image" content="http://www.betanightclub.com/images/hidden/guestlist/fbicon.jpg">
    <meta name="author" content="Betatech, justin@betanightclub.com" />
    <title>$title</title>
    <link href='template/style.css' type='text/css' rel='stylesheet' />
    <script src="http://betanightclub.com/js/cufon-yui.js" type="text/javascript"></script>
    <script src="http://betanightclub.com/js/Social_Gothic_400.font.js" type="text/javascript"></script>
    <script src="http://betanightclub.com/js/helper.js" type="text/javascript"></script>
    $banner
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-8872962-6', 'auto');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <div id="centeredcontent">
      <div id="masthead">Beta Nightclub</div>
      <h2>$title</h2>
      <p>This form allows you guest entry on {$artist->name}&#39;s list at the guest list door for the following lists:
        <br />21+: $price21
        <br />18+: $price18
      </p>
      $links
      <hr />
      <form action="?a=signup" method="POST" id="signup_form">
        <table class="formtable">
          <tr>
            <td>
              <input type="hidden" name="signup_event" value="{$event->id}" />
              <label for="signup_name" class="formtitle cfont">First &amp; Last Name:</label>
              <br /><input type="text" name="signup_name" value="" id="signup_name" autofocus="autofocus" required="required" />
            </td>
            <td>
              <label for="signup_email"><span class="formtitle cfont">Email Address:</span> <span class="smallertext">Checked for validity</span></label>
              <br /><input type="email" name="signup_email" value="" id="signup_email" required="required" />
            </td>
          </tr>
          <tr>
            <td class="halfwidth">
              <label for="signup_age" class="formtitle cfont">Age:</label>
              $option_21plus
              $option_18plus
            </td>
            <td class="halfwidth">
              <label for="signup_gender" class="formtitle cfont">Gender:</label>
              <br /><label><input type="radio" name="signup_gender" value="female" id="signup_gender_female" required="required" />Female</label>
              <br /><label><input type="radio" name="signup_gender" value="male" id="signup_gender_male" />Male</label>
            </td>
          </tr>
$extrafields
        </table>
        <input type="submit" name="signup_submit" value="Submit" />
        <p class="smalltext">By filling out this form you agree to allow Beta Nightclub (including {$artist->name}$promoter) to send you email updates about upcoming events and special offers. [Beta Nightclub and associated promotion groups do not share your personal information.]</p>
      </form>
      <hr />
    </div><!-- #centeredcontent -->
    <script type="text/javascript"> Cufon.now(); </script>
  </body>
</html>
END;
?>