<?php
/*
Guest List Confirmation Template - present a confirmation page to customer

This template uses standard PHP inline echo format (ex: <?= $myVar ?>, <?php echo $something ?>)

The following variables and objects are available in this template:
* $event (object)
    * $event->id - system specific ID for event (used when submitting form data)
    * $event->year - YYYY
    * $event->month - MM
    * $event->day - DD
    * $event->headliner - Headliner
* $age - text string representing age group of list applied for (ex: "21")
* $settings (object)
*/
?>
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Thank you for signing up on the guest list." />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="image_src" href="/gl/template/fbicon.jpg" />
    <meta property="og:image" content="http://www.betanightclub.com/fbthumb.jpg" />
    <meta property="og:description" content="Thank you for signing up on the guest list." />
    <meta name="author" content="Justin Ryan, justin@betanightclub.com" />
    <title><?php echo strtoupper(substr(date("D", $showtime),0,2))."/".$event->month."/".$event->day." :: ".$artist."&#39;s Guest List :: ".$event->headliner; ?></title>
    <link href='template/style.css' type='text/css' rel='stylesheet' />
    <?php echo $banner; ?>
  </head>
  <body>
    <div id="centeredcontent">
      <div id="masthead">Guest List Sign Up</div>
      <h2>Thanks for signing up <?php $freeloader = explode(" ", $user, 2); echo $freeloader[0]; ?>!</h1>
      <h3>You've been added to the <?php echo $age; ?>+ guest list for <?php echo $event->headliner; ?> on <?php echo date("l", $showtime).", ".$settings['misc']['months'][sprintf('%02d', $event->month)]." ".$settings['misc']['days'][sprintf('%02d', $event->day)]; ?>.</h3>
      <h4>The prices for this list are: <?php echo ($age == "21") ? $settings['prices']['21'][$event->pricing_21] : $settings['prices']['18'][$event->pricing_18]; ?>.</h4>
      <p>This sign-up form cuts off at <?= $timestr ?> MST. If you have signed up after <?= $timestr ?>, you will not be added to the guest list. List prices subject to change.</p>
      <hr>
    </div><!-- #centeredcontent -->
  </body>
</html>