<?php
/*
Guest List Error Template - inform the customer of an error message

Templates follow the PHP Heredoc format: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
Variables are parsed using PHP double quote syntax (ex: "My $variable, your {$you->variable}, our \'\$variables\'")

The following variables and objects are available in this template:
* $title - short title of error
* $message - long title of error
* $content - HTML long description of error
* $error - system specific, single word error ID descriptor (used for analytics purposes, for example)
* $settings (object)
*/
return <<<END
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="$message" />
    <link rel="shortcut icon" href="http://www.betanightclub.com/favicon.ico" type="image/x-icon" />
    <link rel="image_src" href="http://www.betanightclub.com/images/hidden/guestlist/fbicon.jpg" />
    <meta property="og:image" content="http://www.betanightclub.com/fbthumb.jpg" />
    <meta property="og:description" content="$message" />
    <meta name="author" content="Justin Ryan, justin@betanightclub.com" />
    <title>$title</title>
    <link href='template/style.css' type='text/css' rel='stylesheet' />
    <script src="http://betanightclub.com/js/cufon-yui.js" type="text/javascript"></script>
    <script src="http://betanightclub.com/js/Social_Gothic_400.font.js" type="text/javascript"></script>
    <script src="http://betanightclub.com/js/helper.js" type="text/javascript"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-8872962-6', 'auto');
      ga('send', 'pageview', '{$_SERVER['REQUEST_URI']}/$error');
    </script>
  </head>
  <body>
    <div id="centeredcontent">
      <div id="masthead">Beta Nightclub</div>
      <h2>$message</h2>
$content
      <p>Tickets can be purchased online, until 8pm MST, through Beta Nightclub&apos;s website by <a href="https://www.betanightclub.com/events">clicking here</a>, or through <a href="http://betanightclub.electrostub.com/">our affiliate ElectroStub</a>. Tickets can also be purchased at Beta Nightclub&apos;s box-office, day of show, starting at 9pm MST (7pm Sundays) until close.</p>
    </div><!-- #centeredcontent -->
    <script type="text/javascript"> Cufon.now(); </script>
  </body>
</html>
END;
?>