<?php
/*
Guest List Error Template - inform the customer of an error message

Templates follow the PHP Heredoc format: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
Variables are parsed using PHP double quote syntax (ex: "My $variable, your {$you->variable}, our \'\$variables\'")

The following variables and objects are available in this template:
* $title - short title of error
* $message - long title of error
* $content - HTML long description of error
* $error - system specific, single word error ID descriptor (used for analytics purposes, for example)
* $settings (object)
*/
return <<<END
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="$message" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="image_src" href="/gl/template/fbicon.jpg" />
    <meta property="og:image" content="/gl/template/fbthumb.jpg" />
    <meta property="og:description" content="$message" />
    <meta name="author" content="Justin Ryan, justin@betanightclub.com" />
    <title>$title</title>
    <link href='template/style.css' type='text/css' rel='stylesheet' />
  </head>
  <body>
    <div id="centeredcontent">
      <div id="masthead">Guest List Sign Up</div>
      <h2>$message</h2>
$content
      <p>Tickets can be purchased online, until 8pm MST, through our website. Tickets can also be purchased at the box-office, day of show, starting at 9pm MST (7pm Sundays) until close.</p>
    </div><!-- #centeredcontent -->
  </body>
</html>
END;
?>